# ~/.config/yazi/yazi.toml
[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Editor" },
]

[open]
rules = [
    { mime = "text/*", use = "edit" },
    { name = "*", use = "edit" },
]

[mgr]
show_hidden = true
