# ~/.config/yazi/yazi.toml

# yazi 打开文本文件使用nvim
[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Editor" },
]

[open]
rules = [
    { mime = "text/*", use = "edit" },
    { name = "*", use = "edit" },
]

# 默认显示隐藏文件
[mgr]
show_hidden = true
